using System.Collections;
using System.Collections.Generic;
using ProFramework;
using UnityEngine;
using UnityEngine.UI;

namespace ProFrameworkTest
{
    public class AssetBundleTest : MonoBehaviour
    {
        public Image image;

        void Update()
        {
            // 쇱꿎객숩
            if (Input.GetKeyDown(KeyCode.Q))
            {
                ProAssetBundleManager.Instance.LoadResource<GameObject>(ProConst.Models, "CubeTest",
                    (gameObject => { Instantiate(gameObject); }));


                ProAssetBundleManager.Instance.LoadResource<GameObject>(ProConst.Models, "CubeTest",
                    (gameObject => { Instantiate(gameObject); }), true);
            }

            // 쇱꿎객숩
            if (Input.GetKeyDown(KeyCode.W))
            {
                ProAssetBundleManager.Instance.UnLoadAssetBundle(ProConst.Materials,
                    (isSuccess) => { ProLog.LogDebug("菌潼Materials관써벎" + isSuccess); }, true);
            }

            // 쇱꿎객숩
            if (Input.GetKeyDown(KeyCode.E))
            {
                ProAssetBundleManager.Instance.UnLoadAssetBundle(ProConst.Models,
                    (isSuccess) => { ProLog.LogDebug("菌潼Model관써벎" + isSuccess); }, true);
            }

            // 쇱꿎객숩
            if (Input.GetKeyDown(KeyCode.R))
            {
                ProAssetBundleManager.Instance.LoadResource<Material>(ProConst.Materials,"RedMaterialTest",
                    (isSuccess) => { ProLog.LogDebug("RedMaterialTest속潼써벎" + isSuccess); }, true);
            }
            

            if (Input.GetKeyDown(KeyCode.T))
            {
                ProAssetBundleManager.Instance.LoadResource<Sprite>(ProConst.Textures, "head",
                    (sprite => { image.sprite = sprite; }));
            }
        }
    }
}